# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mmou/Documents/YULcode

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mmou/Documents/YULcode

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mmou/Documents/YULcode/CMakeFiles /home/mmou/Documents/YULcode/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mmou/Documents/YULcode/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

carte.o: carte.cpp.o

.PHONY : carte.o

# target to build an object file
carte.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/carte.cpp.o
.PHONY : carte.cpp.o

carte.i: carte.cpp.i

.PHONY : carte.i

# target to preprocess a source file
carte.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/carte.cpp.i
.PHONY : carte.cpp.i

carte.s: carte.cpp.s

.PHONY : carte.s

# target to generate assembly for a file
carte.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/carte.cpp.s
.PHONY : carte.cpp.s

case.o: case.cpp.o

.PHONY : case.o

# target to build an object file
case.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/case.cpp.o
.PHONY : case.cpp.o

case.i: case.cpp.i

.PHONY : case.i

# target to preprocess a source file
case.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/case.cpp.i
.PHONY : case.cpp.i

case.s: case.cpp.s

.PHONY : case.s

# target to generate assembly for a file
case.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/case.cpp.s
.PHONY : case.cpp.s

coord.o: coord.cpp.o

.PHONY : coord.o

# target to build an object file
coord.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/coord.cpp.o
.PHONY : coord.cpp.o

coord.i: coord.cpp.i

.PHONY : coord.i

# target to preprocess a source file
coord.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/coord.cpp.i
.PHONY : coord.cpp.i

coord.s: coord.cpp.s

.PHONY : coord.s

# target to generate assembly for a file
coord.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/coord.cpp.s
.PHONY : coord.cpp.s

employer.o: employer.cpp.o

.PHONY : employer.o

# target to build an object file
employer.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/employer.cpp.o
.PHONY : employer.cpp.o

employer.i: employer.cpp.i

.PHONY : employer.i

# target to preprocess a source file
employer.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/employer.cpp.i
.PHONY : employer.cpp.i

employer.s: employer.cpp.s

.PHONY : employer.s

# target to generate assembly for a file
employer.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/employer.cpp.s
.PHONY : employer.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

plan.o: plan.cpp.o

.PHONY : plan.o

# target to build an object file
plan.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/plan.cpp.o
.PHONY : plan.cpp.o

plan.i: plan.cpp.i

.PHONY : plan.i

# target to preprocess a source file
plan.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/plan.cpp.i
.PHONY : plan.cpp.i

plan.s: plan.cpp.s

.PHONY : plan.s

# target to generate assembly for a file
plan.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/plan.cpp.s
.PHONY : plan.cpp.s

salle.o: salle.cpp.o

.PHONY : salle.o

# target to build an object file
salle.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/salle.cpp.o
.PHONY : salle.cpp.o

salle.i: salle.cpp.i

.PHONY : salle.i

# target to preprocess a source file
salle.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/salle.cpp.i
.PHONY : salle.cpp.i

salle.s: salle.cpp.s

.PHONY : salle.s

# target to generate assembly for a file
salle.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/salle.cpp.s
.PHONY : salle.cpp.s

visualizer.o: visualizer.cpp.o

.PHONY : visualizer.o

# target to build an object file
visualizer.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/visualizer.cpp.o
.PHONY : visualizer.cpp.o

visualizer.i: visualizer.cpp.i

.PHONY : visualizer.i

# target to preprocess a source file
visualizer.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/visualizer.cpp.i
.PHONY : visualizer.cpp.i

visualizer.s: visualizer.cpp.s

.PHONY : visualizer.s

# target to generate assembly for a file
visualizer.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/visualizer.cpp.s
.PHONY : visualizer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... edit_cache"
	@echo "... carte.o"
	@echo "... carte.i"
	@echo "... carte.s"
	@echo "... case.o"
	@echo "... case.i"
	@echo "... case.s"
	@echo "... coord.o"
	@echo "... coord.i"
	@echo "... coord.s"
	@echo "... employer.o"
	@echo "... employer.i"
	@echo "... employer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... plan.o"
	@echo "... plan.i"
	@echo "... plan.s"
	@echo "... salle.o"
	@echo "... salle.i"
	@echo "... salle.s"
	@echo "... visualizer.o"
	@echo "... visualizer.i"
	@echo "... visualizer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

